task-15 done
dezmorales/testguru pull request #14
Opened 2022-10-15 14:15 UTC by dezmorales

2022-10-15 17:21 UTC, BubuntuClu requested changes

2022-10-15 17:21 UTC, BubuntuClu commented on app/javascript/packs/registrtion.js
> +    if (confirmation.value == '') { return null }
`Не информируйте пользователя если поле подтверждения пароля не содержит значения`

если что-то ввести и потом очистить, то выделение компонентов не очистится.

`null` возвращать не обязательно, можно пустой ретурн сделать

2022-10-19 14:51 UTC, VidgarVii requested changes

2022-10-19 14:51 UTC, VidgarVii commented on app/assets/stylesheets/application.scss
> +@import "global";
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file

2022-10-19 14:51 UTC, VidgarVii commented on app/javascript/packs/registration.js
> +    let control = document.querySelector('#new_user')
есть более удобный и быстрый способы искать элемент по ИД 
getElementById
https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById

2022-10-19 14:51 UTC, VidgarVii commented on app/javascript/packs/registration.js
> +    let alert = document.querySelector('.octicon-alert')
на каждое срабатывание событие происходит поиск элементов. Когда можно это делать 1 раз и не мучить ресурсы компьютера клиента

2022-10-19 14:51 UTC, VidgarVii commented on app/javascript/packs/registration.js
> +    let control = document.querySelector('#new_user')
если переменная не переопределяется, то принято считать её константой. Так безопасней

2022-10-19 14:51 UTC, VidgarVii commented on app/javascript/packs/registration.js
> +}
Вообще я бы посоветовал потренироваться в ООП. JS позволяет создавать классы и браузеры это понимают, пусть пока и без инкапсуляций, но уже хоть что-то.
По пробуй создать такой класс утилиту, который принимает html элемент. И далее пусть эта утилита работает только с этим элементов. Таким образом мы сможем пере использоваться утилиту сколько угодно раз с разными элементами без переписывания кода. И так вся логика функционала будет обёрнута в класс, а не просто болтаться где-то снаружи. 
http://old.code.mu/books/javascript/oop/

2022-10-21 03:59 UTC, VidgarVii requested changes

2022-10-21 03:59 UTC, VidgarVii commented on app/assets/stylesheets/global.scss
> +}
https://github.com/dezmorales/testguru/pull/14#discussion_r999559665
Это надо везде убрать!

2022-10-21 03:59 UTC, VidgarVii commented on app/javascript/packs/registration.js
> +}
https://github.com/dezmorales/testguru/pull/14#discussion_r999559665

2022-10-21 03:59 UTC, VidgarVii commented on app/javascript/utilities/sorting.js
> +}
https://github.com/dezmorales/testguru/pull/14#discussion_r999559665

2022-10-23 15:06 UTC, merged