add badges for user
dezmorales/testguru pull request #17
Opened 2022-11-16 21:22 UTC by dezmorales

2022-11-17 07:11 UTC, BubuntuClu requested changes

2022-11-17 07:11 UTC, BubuntuClu commented on app/models/badge.rb
> +  enum rule: {
добавь еще правило на все тесты уровня

2022-11-17 07:11 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    passed = @user.test_passages.find_all { |test_passage| test_passage.successful? }.map { |tp| tp.test }.uniq
тут не должно быть обработки данных через руби. данные должны быть максимально отфильтрованны на уровне БД.
по сути тут в методе будет два запроса к БД и сравнение их результатов

2022-11-17 07:11 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    return unless badge.subject_name == @test.category.title
замени `unless` на `if`, так будет легче код восприниматься

2022-11-17 07:12 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    passed = @user.test_passages.find_all { |test_passage| test_passage.successful? }.map { |tp| tp.test }.uniq
у тебя есть метод поиск тестов по имени категорий, можно этот метод применить в этом правиле бейджа

2022-11-18 17:25 UTC, BubuntuClu requested changes

2022-11-18 17:25 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    successful_tests = Test.joins(:test_passages).where(category: @category,
`where(category: @category,` - как работает эта часть запроса? у тебя нет таких столбцов в таблице тестов и прохождений

2022-11-18 17:25 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    @level = @test.level
зачем тебе эта инстанс переменная для всего сервиса? ты вызываешь ее в одном конкретном метода, там и объяви ее

2022-11-18 17:25 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    @category = @test.category
и это тоже

2022-11-18 18:00 UTC, dezmorales commented on app/services/badge_service.rb
> +    successful_tests = Test.joins(:test_passages).where(category: @category,
В этом месте я ищу по таблице тестов, в тестах есть ассоциация на категории

2022-11-19 14:30 UTC, merged